// Shared OOXML rebranding core — the single source of truth for the document
// logic. Inlined into index.html between the CORE markers by build.mjs, and
// imported directly by the Node test harness (test/setup.mjs). Depends only on
// globals available in both environments: DOMParser, XMLSerializer, crypto, and
// fflate (real fflate in-browser; a node:zlib shim under Node).
    export const NS={w:"http://schemas.openxmlformats.org/wordprocessingml/2006/main",r:"http://schemas.openxmlformats.org/officeDocument/2006/relationships",a:"http://schemas.openxmlformats.org/drawingml/2006/main",wp:"http://schemas.openxmlformats.org/drawingml/2006/wordprocessingDrawing",pic:"http://schemas.openxmlformats.org/drawingml/2006/picture",rel:"http://schemas.openxmlformats.org/package/2006/relationships",ct:"http://schemas.openxmlformats.org/package/2006/content-types",w14:"http://schemas.microsoft.com/office/word/2010/wordml",xml:"http://www.w3.org/XML/1998/namespace"};
    export const LABELS={doknrversionnr:"dok_nr",thematik:"thematik",bearbeiter:"bearbeiter",freigeber:"freigeber",prozessverantwortung:"prozessverantwortung",unterkategorie:"unterkategorie",prufer:"pruefer",freigabedatum:"freigabedatum"};
    export function parse(bytes){const s=typeof bytes==="string"?bytes:fflate.strFromU8(bytes);const d=new DOMParser().parseFromString(s,"application/xml");if(d.querySelector("parsererror"))throw Error("Ungültiges XML");return d;}
    export function xml(doc){return fflate.strToU8('<?xml version="1.0" encoding="UTF-8" standalone="yes"?>\r\n'+new XMLSerializer().serializeToString(doc.documentElement));}
    export function els(node,ns,name){return [...node.getElementsByTagNameNS(ns,name)];}
    export function attr(el,ns,name){if(!el||typeof el.getAttributeNS!=="function")return null;return el.getAttributeNS(ns,name)||el.getAttribute("w:"+name)||el.getAttribute(name);}
    export function setAttr(el,ns,prefix,name,val){el.setAttributeNS(ns,prefix+":"+name,String(val));}
    export function direct(node,ns,name){const out=[];function walk(n){for(const c of n.children||[]){if(c.namespaceURI===ns&&c.localName===name)out.push(c);else if(!(c.namespaceURI===NS.w&&c.localName==="tbl"))walk(c);}}walk(node);return out;}
    export function textIn(tc){let s="";function walk(n){for(const c of n.children||[]){if(c!==tc&&c.namespaceURI===NS.w&&c.localName==="tbl")continue;if(c.namespaceURI===NS.w&&c.localName==="t")s+=c.textContent||"";walk(c);}}walk(tc);return s;}
    export function span(tc){const x=els(tc,NS.w,"gridSpan")[0];return Math.max(1,Number(attr(x,NS.w,"val"))||1);}
    export function grid(tbl){return direct(tbl,NS.w,"tr").map(tr=>{const row=[];for(const tc of direct(tr,NS.w,"tc")){row.push(tc);for(let i=1;i<span(tc);i++)row.push(tc);}return {tr,row};});}
    export function norm(s){return (s||"").normalize("NFD").replace(/[\u0300-\u036f]/g,"").toLowerCase().replace(/[^a-z0-9]/g,"");}
    export function label(s){const n=norm(s);if(LABELS[n])return LABELS[n];let best="";for(const x of Object.keys(LABELS))if(n.startsWith(x)&&x.length>best.length)best=x;return best?LABELS[best]:null;}
    export function metaTables(doc){const out=[];for(const tbl of els(doc,NS.w,"tbl")){const rows=grid(tbl),cells={};rows.forEach(({row},i)=>row.forEach((tc,j)=>{const k=label(textIn(tc));if(k&&rows[i+1]?.row[j])cells[k]??=rows[i+1].row[j];}));if(cells.bearbeiter&&cells.freigeber)out.push({tbl,cells});}return out;}
    export function relMap(parts,part){const slash=part.lastIndexOf("/"),rn=part.slice(0,slash)+"/_rels/"+part.slice(slash+1)+".rels",out={};if(!parts[rn])return out;for(const r of els(parse(parts[rn]),NS.rel,"Relationship")){if(r.getAttribute("TargetMode")==="External")continue;let t=r.getAttribute("Target")||"";t=t.replace(/^\.\.\//,"");if(!t.startsWith("word/")&&!t.startsWith("/"))t="word/"+t;out[r.getAttribute("Id")]=t.replace(/^\//,"");}return out;}
    export function images(parts,part){if(!parts[part])return[];const doc=parse(parts[part]),rels=relMap(parts,part),out=[];for(const kind of ["anchor","inline"]){for(const n of els(doc,NS.wp,kind)){const ext=els(n,NS.wp,"extent")[0],blip=els(n,NS.a,"blip")[0],rid=blip&&(blip.getAttributeNS(NS.r,"embed")||blip.getAttribute("r:embed"));out.push({rid,target:rels[rid],kind,cx:Number(ext?.getAttribute("cx"))||0,cy:Number(ext?.getAttribute("cy"))||0});}}return out;}
    export function inspect(parts,steps){steps=steps||{logo:true,meta:true,changelog:true,company:false};const names=Object.keys(parts);if(!parts["word/document.xml"])return {ok:false,reason:"Kein gültiges DOCX"};const headers=names.filter(n=>/^word\/header\d+\.xml$/.test(n)),footers=names.filter(n=>/^word\/footer\d+\.xml$/.test(n));const result={ok:true,headers,footers},notes=[];if(steps.logo){const hi=headers.flatMap(h=>images(parts,h).map(x=>({...x,part:h}))),targets=new Set(hi.map(x=>x.target).filter(Boolean));if(!targets.size)return {ok:false,reason:"Kein Bild im Header"};if(targets.size!==1)return {ok:false,reason:"Mehrere Header-Bilder; Logo nicht eindeutig"};const target=[...targets][0],bodyTargets=new Set(images(parts,"word/document.xml").map(x=>x.target));if(bodyTargets.has(target))return {ok:false,reason:"Logo-Mediendatei wird auch im Dokument verwendet"};if(!hi.some(x=>x.target===target&&x.cx&&x.cy))return {ok:false,reason:"Keine Logo-Größe gefunden"};result.target=target;result.hi=hi;notes.push(`${headers.length} Header`);}if(steps.meta||steps.changelog){let metas=0;for(const n of [...headers,"word/document.xml",...footers])if(parts[n])metas+=metaTables(parse(parts[n])).length;if(!metas)return {ok:false,reason:"Metadatentabelle nicht gefunden"};notes.push(`${metas} Metadatentabelle(n)`);}if(steps.company)notes.push("Firma-Ersetzung");result.reason=notes.join(", ")||"Bereit";return result;}
    export function setCell(tc,value){const ts=els(tc,NS.w,"t");if(!ts.length){const doc=tc.ownerDocument,p=doc.createElementNS(NS.w,"w:p"),r=doc.createElementNS(NS.w,"w:r"),t=doc.createElementNS(NS.w,"w:t");t.textContent=value;r.append(t);p.append(r);tc.append(p);return;}ts[0].textContent=value;for(const t of ts.slice(1))t.textContent="";}
    export function bump(s){const m=(s||"").trim().match(/^(.*?)(\d+)\.(\d+)$/);if(!m)return null;const v=`${Number(m[2])+1}.0`;return {text:m[1]+v,version:v,old:`${m[2]}.${m[3]}`};}
    export function id(){const a=new Uint32Array(1);crypto.getRandomValues(a);return (a[0]&0x7ffffffe).toString(16).toUpperCase().padStart(8,"0");}
    export function changelogLine(version,date){const label=`Version ${version}`;return label+" ".repeat(Math.max(1,33-label.length))+date;}
    export function cloneChangelog(doc,version,date,change){for(const tbl of els(doc,NS.w,"tbl")){const rows=grid(tbl),matches=rows.filter(x=>textIn(x.row[0]||{}).trim().toLowerCase().startsWith("version"));if(!matches.length)continue;const sample=textIn(matches.at(-1).row[0]||{}),gap=sample.match(/^(Version\s+\S+)(\s+)(\S+)/i)?.[2]||"  ";const tr=matches.at(-1).tr.cloneNode(true);for(const x of [tr,...tr.querySelectorAll("*")]){if(x.hasAttributeNS(NS.w14,"paraId"))setAttr(x,NS.w14,"w14","paraId",id());if(x.hasAttributeNS(NS.w14,"textId"))setAttr(x,NS.w14,"w14","textId",id());}const cs=direct(tr,NS.w,"tc");if(cs.length<2)return false;setCell(cs[0],`Version ${version}${gap}${date}`);setCell(cs[1],change);cs.slice(2).forEach(x=>setCell(x,""));tbl.append(tr);return true;}return false;}
    export function addChangelog(doc,oldVersion,oldDate,version,date,change){const body=els(doc,NS.w,"body")[0];if(!body)return false;const make=(n)=>doc.createElementNS(NS.w,"w:"+n),tbl=make("tbl"),pr=make("tblPr"),borders=make("tblBorders");for(const n of ["top","left","bottom","right","insideH","insideV"]){const b=make(n);setAttr(b,NS.w,"w","val","single");setAttr(b,NS.w,"w","sz","4");borders.append(b);}pr.append(borders);tbl.append(pr);for(const vals of [[changelogLine(oldVersion,oldDate),"Neuerstellung"],[changelogLine(version,date),change]]){const tr=make("tr");for(const val of vals){const tc=make("tc"),p=make("p"),r=make("r"),t=make("t");t.textContent=val;r.append(t);p.append(r);tc.append(p);tr.append(tc);}tbl.append(tr);}const sect=[...body.children].find(x=>x.namespaceURI===NS.w&&x.localName==="sectPr");body.insertBefore(tbl,sect||null);body.insertBefore(make("p"),sect||null);return true;}
    export function patch(parts,inspection,logoBytes,dims,o){
      const names=Object.keys(parts),steps=o.steps||{logo:true,meta:true,changelog:true,company:false},headers=inspection.headers;
      if(steps.logo){
        const oldMedia=inspection.target,logoExt=(o.logoName.split(".").pop()||"jpg").toLowerCase().replace("jpg","jpeg"),oldExt=oldMedia.split(".").pop().toLowerCase(),same=(oldExt===logoExt)||([oldExt,logoExt].every(x=>["jpg","jpeg"].includes(x))),newMedia=`word/media/logo_rebrand.${logoExt}`,newRids={};
        if(same)parts[oldMedia]=logoBytes;else{parts[newMedia]=logoBytes;for(const h of headers){const rn=`word/_rels/${h.split("/").pop()}.rels`,rd=parse(parts[rn]),rels=els(rd,NS.rel,"Relationship"),nums=rels.map(x=>Number((x.getAttribute("Id")||"").match(/^rId(\d+)$/)?.[1])||0),rid=`rId${Math.max(0,...nums)+1}`,r=rd.createElementNS(NS.rel,"Relationship");r.setAttribute("Id",rid);r.setAttribute("Type","http://schemas.openxmlformats.org/officeDocument/2006/relationships/image");r.setAttribute("Target",newMedia.replace("word/",""));rd.documentElement.append(r);for(const x of rels){let t=(x.getAttribute("Target")||"").replace(/^\.\.\//,"");if("word/"+t.replace(/^\//,"")===oldMedia)x.remove();}parts[rn]=xml(rd);newRids[h]=rid;}const cd=parse(parts["[Content_Types].xml"]),have=els(cd,NS.ct,"Default").some(x=>(x.getAttribute("Extension")||"").toLowerCase()===logoExt);if(!have){const x=cd.createElementNS(NS.ct,"Default");x.setAttribute("Extension",logoExt);x.setAttribute("ContentType",logoExt==="png"?"image/png":logoExt==="gif"?"image/gif":"image/jpeg");cd.documentElement.append(x);}parts["[Content_Types].xml"]=xml(cd);}
        const aspect=dims[0]/dims[1];let placements=0;for(const h of headers){const hd=parse(parts[h]),oldRids=new Set(inspection.hi.filter(x=>x.part===h&&x.target===oldMedia).map(x=>x.rid));if(!same)for(const b of els(hd,NS.a,"blip")){const rid=b.getAttributeNS(NS.r,"embed")||b.getAttribute("r:embed");if(oldRids.has(rid))setAttr(b,NS.r,"r","embed",newRids[h]);}for(const x of els(hd,NS.pic,"cNvPr"))if(x.hasAttribute("descr"))x.setAttribute("descr",o.logoName);for(const kind of ["anchor","inline"])for(const n of els(hd,NS.wp,kind)){const ex=els(n,NS.wp,"extent")[0];if(!ex)continue;const ocx=Number(ex.getAttribute("cx")),ocy=Number(ex.getAttribute("cy"));if(!ocx||!ocy)continue;const ncx=o.width,ncy=Math.round(ncx/aspect);ex.setAttribute("cx",ncx);ex.setAttribute("cy",ncy);for(const ae of els(n,NS.a,"ext"))if(ae.hasAttribute("cx")){ae.setAttribute("cx",ncx);ae.setAttribute("cy",ncy);}if(kind==="anchor"){const ph=els(n,NS.wp,"positionH")[0],pv=els(n,NS.wp,"positionV")[0],ho=ph&&els(ph,NS.wp,"posOffset")[0],vo=pv&&els(pv,NS.wp,"posOffset")[0];if(ho&&/^-?\d+$/.test(ho.textContent.trim()))ho.textContent=Number(ho.textContent)+ocx-ncx;if(vo&&/^-?\d+$/.test(vo.textContent.trim()))vo.textContent=Math.round(Number(vo.textContent)+ocy/2-ncy/2);}placements++;}parts[h]=xml(hd);}if(!placements)throw Error("Logo konnte nicht skaliert werden");
      }
      let version="",oldVersion="",oldDate="",metaCount=0;
      if(steps.meta||steps.changelog){
        const metaParts=[...headers,"word/document.xml",...names.filter(n=>/^word\/footer\d+\.xml$/.test(n))];
        for(const pn of metaParts){if(!parts[pn])continue;const d=parse(parts[pn]),mts=metaTables(d);for(const {cells} of mts){if(steps.meta){setCell(cells.bearbeiter,o.bearbeiter);setCell(cells.freigeber,o.freigeber);if(cells.pruefer)setCell(cells.pruefer,o.pruefer);}if(cells.freigabedatum){oldDate||=textIn(cells.freigabedatum).trim();if(steps.meta){for(const x of els(cells.freigabedatum,NS.w,"date"))setAttr(x,NS.w,"w","fullDate",o.iso);setCell(cells.freigabedatum,o.date);}}if(cells.dok_nr){const b=bump(textIn(cells.dok_nr));if(b){version||=b.version;oldVersion||=b.old;if(steps.meta)setCell(cells.dok_nr,b.text);}}metaCount++;}if(mts.length&&steps.meta)parts[pn]=xml(d);}
        if(!version)throw Error("Versionsnummer in Dok.-Nr. nicht erkannt");
      }
      if(steps.changelog){const dd=parse(parts["word/document.xml"]);if(!cloneChangelog(dd,version,o.date,o.changelog)){if(!oldDate)throw Error("Changelog fehlt und altes Datum ist leer");addChangelog(dd,oldVersion||"1.0",oldDate,version,o.date,o.changelog);}parts["word/document.xml"]=xml(dd);}
      let company={count:0,tracked:!!o.companyTracked,fallbacks:[]};
      if(steps.company&&o.companyFrom)company=replaceCompany(parts,o);
      const out=fflate.zipSync(parts,{level:6});
      verify(out,o,metaCount);
      return {bytes:out,company};
    }
    export function verify(bytes,o,count){const p=fflate.unzipSync(bytes),steps=o.steps||{meta:true,changelog:true};for(const [n,b] of Object.entries(p))if(n.endsWith(".xml")||n.endsWith(".rels"))parse(b);if(steps.meta){let found=0;for(const [n,b] of Object.entries(p))if(/^word\/(document|header\d+|footer\d+)\.xml$/.test(n)){for(const {cells} of metaTables(parse(b))){for(const [k,want] of Object.entries({bearbeiter:o.bearbeiter,freigeber:o.freigeber,pruefer:o.pruefer,freigabedatum:o.date}))if(cells[k]&&textIn(cells[k]).trim()!==want)throw Error(`Prüfung fehlgeschlagen: ${k}`);found++;}}if(found!==count)throw Error("Prüfung der Metadatentabellen fehlgeschlagen");}if(steps.changelog){const all=fflate.strFromU8(p["word/document.xml"]);if(!all.includes(o.changelog))throw Error("Changelog-Prüfung fehlgeschlagen");}}
    export function escapeRegex(s){return String(s).replace(/[.*+?^${}()|[\]\\]/g,"\\$&");}
    export function replaceCompany(parts,o){const from=o.companyFrom||"",to=o.companyTo??"",tracked=!!o.companyTracked;if(!from)return {count:0,tracked,fallbacks:[]};const targetNames=Object.keys(parts).filter(n=>/^word\/(document|header\d+|footer\d+)\.xml$/.test(n));let count=0;const fallbacks=[];for(const pn of targetNames){if(!parts[pn])continue;const doc=parse(parts[pn]),rev={n:revBase(doc)};let changed=false;for(const p of els(doc,NS.w,"p")){const res=tracked?replaceParagraphTracked(doc,p,from,to,o,rev):replaceParagraphPlain(doc,p,from,to);if(res.count){count+=res.count;changed=true;}for(const s of res.fallbacks)fallbacks.push({part:pn.replace(/^word\//,""),snippet:s});}if(changed)parts[pn]=xml(doc);}return {count,tracked,fallbacks};}
    function revBase(doc){let mx=0;for(const tag of ["ins","del"])for(const el of els(doc,NS.w,tag)){const v=Number(attr(el,NS.w,"id"));if(v>mx)mx=v;}return mx+1;}
    function runTextOf(r){return els(r,NS.w,"t").map(t=>t.textContent||"").join("");}
    function makeRun(srcRun,doc,text,tag){const r=srcRun.cloneNode(true);for(const x of els(r,NS.w,"t").slice(1))x.remove();for(const x of els(r,NS.w,"delText"))x.remove();let t=els(r,NS.w,"t")[0];if(!t){t=doc.createElementNS(NS.w,"w:t");r.append(t);}if(tag==="delText"){const d=doc.createElementNS(NS.w,"w:delText");t.parentNode.replaceChild(d,t);t=d;}t.textContent=text;t.setAttributeNS(NS.xml,"xml:space","preserve");return r;}
    function wrapRev(doc,tag,runEl,o,rev){const el=doc.createElementNS(NS.w,"w:"+tag);setAttr(el,NS.w,"w","id",String(rev.n++));setAttr(el,NS.w,"w","author",o.author||"Rebranding");setAttr(el,NS.w,"w","date",o.iso||new Date().toISOString());el.append(runEl);return el;}
    function ctx(full,i,len){const a=Math.max(0,i-15),b=Math.min(full.length,i+len+15);return (a>0?"…":"")+full.slice(a,b).replace(/\s+/g," ").trim()+(b<full.length?"…":"");}
    function replaceParagraphPlain(doc,p,from,to){const ts=els(p,NS.w,"t");if(!ts.length)return {count:0,fallbacks:[]};const mk=()=>new RegExp(escapeRegex(from),"gi");let count=0;for(const t of ts){const b=t.textContent||"",a=b.replace(mk(),to);if(a!==b){count+=(b.match(mk())||[]).length;t.textContent=a;}}const full=ts.map(t=>t.textContent||"").join(""),cross=full.match(mk());if(cross){count+=cross.length;ts[0].textContent=full.replace(mk(),to);for(const t of ts.slice(1))t.textContent="";}return {count,fallbacks:[]};}
    function replaceParagraphTracked(doc,p,from,to,o,rev){const runs=[...els(p,NS.w,"r")].filter(r=>els(r,NS.w,"t").length);if(!runs.length)return {count:0,fallbacks:[]};const texts=runs.map(runTextOf),full=texts.join(""),matches=[...full.matchAll(new RegExp(escapeRegex(from),"gi"))];if(!matches.length)return {count:0,fallbacks:[]};const bounds=[];let acc=0;for(const t of texts){bounds.push([acc,acc+t.length]);acc+=t.length;}const runIndexAt=pos=>{for(let i=0;i<bounds.length;i++)if(pos>=bounds[i][0]&&pos<bounds[i][1])return i;return -1;};const isSingle=m=>{const s=runIndexAt(m.index),e=runIndexAt(m.index+m[0].length-1);return s!==-1&&s===e;};if(!matches.every(isSingle)){const fallbacks=matches.filter(m=>!isSingle(m)).map(m=>ctx(full,m.index,m[0].length));const allTs=els(p,NS.w,"t");if(allTs.length){allTs[0].textContent=full.replace(new RegExp(escapeRegex(from),"gi"),to);for(const t of allTs.slice(1))t.textContent="";}return {count:matches.length,fallbacks};}let count=0;for(let ri=0;ri<runs.length;ri++){const r=runs[ri],text=texts[ri],re=new RegExp(escapeRegex(from),"gi");if(!re.test(text))continue;re.lastIndex=0;const frag=[];let last=0,m;while((m=re.exec(text))){const before=text.slice(last,m.index);if(before)frag.push(makeRun(r,doc,before,"t"));frag.push(wrapRev(doc,"del",makeRun(r,doc,m[0],"delText"),o,rev));frag.push(wrapRev(doc,"ins",makeRun(r,doc,to,"t"),o,rev));last=m.index+m[0].length;count++;if(m[0].length===0)re.lastIndex++;}const after=text.slice(last);if(after)frag.push(makeRun(r,doc,after,"t"));const parent=r.parentNode;for(const node of frag)parent.insertBefore(node,r);parent.removeChild(r);}return {count,fallbacks:[]};}
